---
title: "Tarea3"
author: "Norberto Florez"
date: "26/4/2021"
output: html_document
---

```{r Punto 1}
# Punto 1

"Cread un vector llamado Harry formado por la sucesión de números consecutivos entre el -10 y 27. Pedidle a R que os devuelva el elemento de índice 7. Escribid el resultado."

Harry = -10:27
Harry[7]

```
```{r Punto 2}
# Punto 2

"Dad el máximo de la sucesión (100*2^n -7*3^n) con n=0,...,200"
n = 0:200
vec = 100*2^n - 7*3^n
max(vec)

```

```{r Punto 3}
"Cread la sucesión de números consecutivos entre 0 y 40. A continuación, cread el vector (3*5^n - 1) con n=0,...,40. Ponedle como nombre x. Ahora, dad el subvector de los elementos que son estrictamente mayores que 3.5"

n = 0:40
x = 3*5^n - 1
x[x > 3.5]

```
```{r Punto 4}
"Cread una función que os devuelva la parte real, la imaginaria, el módulo, el argumento y el conjugado de un número, mostrando solo 2 cifras significativas"

F = function(num_imag){
  parte_real = Re(num_imag);
  parte_imag = Im(num_imag);
  modulo = Mod(num_imag);
  argum = Arg(num_imag);
  conjug = Conj(num_imag);
  print(parte_real,2)
  print(parte_imag,2)
  print(modulo,2)
  print(argum,2)
  print(conjug,2)
}
F(25.639+58.105i)
```

```{r Punto 5}
"Cread una función que resuelva ecuaciones de segundo grado (de la forma Ax^2+Bx+C=0). No importa, por ahora, que tengáis en cuenta las que no tienen solución"

G = function(A,B,C){
  x1 = (-B + sqrt(B^2-4*A*C)) / (2*A)
  x2 = (-B - sqrt(B^2-4*A*C)) / (2*A)
  print(x1)
  print(x2)
}
G(1,-3,2)
```
```{r Punto 6}
"Tomando el vector vec = c(0,9,98,2,6,7,5,19,88,20,16,0), dad 3 opciones diferentes para calcular el subvector c(9,19,20,16)"

vec = c(0,9,98,2,6,7,5,19,88,20,16,0)
opcion1 = vec[vec>8 & vec<18 | vec>18 & vec<21]
opcion2 = vec[c(2,8,10,11)]
opcion3 = vec[-c(1,3,4,5,6,7,9,12)]
opcion1
opcion2
opcion3


```


```{r punto 7 - Ejercicio 1}

A = matrix(1:4,2)
Oper = A%*%(A+A)%*%A
Oper[2,2]

```

```{r punto 7 - Ejercicio 2}

B = rbind(c(2,4,-6),c(0,0,3),c(0,-2,5))
eigen(B)$values

```
```{r punto 7 - Ejercicio 3}

C = rbind(c(-48,35,-12),c(-134,95,-32),c(-194,133,-44))
round(eigen(B)$vector,3)

```
```{r punto 7 - Ejercicio 4}

D = rbind(c(-2,-8,-2,3),c(-3,-6,-1,2),c(-9,-22,-3,7),c(-18,-44,-8,15))
qr(D)$rank

```



